#!/bin/bash
#
#crpt to test for loop
#
#
if [ $# -eq 0 ]
then
        echo "Error - Number missing form command line argument"
        echo "Syntax : $0 number"
        echo "Use to print multipication table for given number"
exit 1

fi
n=$1
for i in {1..15}

do
echo " $n * $i = `expr $i \* $n`"
done

